# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29b09cc8e9cba551d129bdb8861e0f087caa22bd76134abf902c4db71197a3a5870a2bfbd07330048dc85bc2a4691ca44f052fcf7058b59fd95b18f807948cdd

test:
  secret_key_base: 25ac902ac7e37ffa41000f6712b4fd6fe72146ba7098075fac8a0ef5e8d257b239ce627ffe2b62e61a3ebc17d0cecbfe68bdbe7be44ace3fff6558b9fe10a488

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: <%= ENV["SECRET_TOKEN"] %>
